### PR TITLE
Feat: added handler methods to intercept jsonapi entity framework

### PR DESCRIPTION
**Pull request by spike83**
- intercept for custom entity manipulations
- current principal is providet into interception methods
  => so we can handle things like user-created or simple authorization tasks

### CODE REVIEW

**Comment by csantero** [comment]
@spike83 I do not want to add a member to `IDocumentMaterializer` if we can avoid it. You can achieve the same effect in your project by making a derived class of `EntityFrameworkDocumentMaterializer` that uses constructor injection of IPrincipal, and it wouldn't require any interface changes in the main library.

**Comment by spike83** [comment]
@csantero ok. How and where would you register the principal?

**Comment by csantero** [comment]
@spike83 In my project I do something like the following using Autofac and Owin:

```
            builder.Register(ctx => HttpContext.Current.GetOwinContext()).As<IOwinContext>();

            builder
                .Register((c, p) =>
                {
                    var owin = c.Resolve<IOwinContext>();
                    return owin.Authentication.User;
                })
                .As<IPrincipal>()
                .InstancePerRequest();
```

Then you can just inject IPrincipal into any request-scoped class's constructor, such as the document materializer.

**Comment by csantero** [comment]
@spike83 do the OnCreate etc. methods need to return the same record they were passed in? It seems to me they could just return Tasks.

**Comment by csantero** [comment]
Thanks!

**Pull request merged**
